[workspace]
authors = ["Krasen Samardzhiev <krasensam@gmail.com>"]
channels = ["conda-forge"]
name = "earthcode"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.5.0,<5"
pystac = ">=1.14.1,<2"
xarray = ">=2025.12.0,<2026"
shapely = ">=2.1.2,<3"
xstac = ">=1.2.0,<2"

# [pypi-dependencies]
# earthcode = { path = ".", editable = true }